/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Bean.DanhMucBean;
import Controller.ChuyenGiaoDien;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.JFrame;
/**
 *
 * @author admin
 */
public class GiaoDienChinh extends javax.swing.JFrame {

    private ChuyenGiaoDien controller;
    private List<DanhMucBean> listItem;

    public ChuyenGiaoDien getController() {
        return controller;
    }

    public void setController(ChuyenGiaoDien controller) {
        this.controller = controller;
    }
    
    
    /**
     * Creates new form NewJFrame
     */
    public GiaoDienChinh() {
        initComponents();
        
        controller = new ChuyenGiaoDien(pnlGiaoDienChinh1);
        controller.setView(pnlMenuBanHang1, lblMenuBanHang1);
        
        listItem = new ArrayList<>();
        listItem.add(new DanhMucBean("BanHang", pnlMenuBanHang1, lblMenuBanHang1));
        listItem.add(new DanhMucBean("SanPham", pnlMenuSanPham1, lblMenuSanPham1));
        listItem.add(new DanhMucBean("KhuyenMai", pnlMenuKhuyenMai1, lblMenuKhuyenMai1));
        listItem.add(new DanhMucBean("HoaDon", pnlMenuHoaDon1, lblMenuHoaDon1));
        listItem.add(new DanhMucBean("NhanVien", pnlMenuNhanVien1, lblMenuNhanVien1));
        listItem.add(new DanhMucBean("KhachHang", pnlMenuKhachHang1, lblMenuKhachHang1));
        listItem.add(new DanhMucBean("ThongKe", pnlMenuThongKe1, lblMenuThongKe1));
        
        controller.setEvent(listItem);
        
        setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            
        // Set giao diện chiếm 100% màn hình
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        Clock();
    }
    
    void Clock() {
        new Thread() {
            public void run() {
                try {
                    while (true) {
                        Calendar lich = new GregorianCalendar();
                        int hour = lich.get(Calendar.HOUR);
                        int min = lich.get(Calendar.MINUTE);
                        int sec = lich.get(Calendar.SECOND);
                        int AM_PM = lich.get(Calendar.AM_PM);

//                        String day_night;
                        if (AM_PM == 1) {
//                            day_night = "PM";
                            hour += 12;
                        } else {
//                            day_night = "AM";
                        }

                        String time = hour + ":" + String.format("%02d", min) + ":" + String.format("%02d", sec);
                        lblClock.setText(time);

                        Thread.sleep(1000);
                    }
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }

            }
        }.start();
    }

    // Thêm phương thức setDanhMuc để chọn danh mục mặc định
    public void setDanhMuc(String danhMuc) {
        for (DanhMucBean item : listItem) {
            if (item.getKind().equalsIgnoreCase(danhMuc)) {
                controller.setView(item.getPnl(), item.getLbl());
                break;
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlMenu1 = new javax.swing.JPanel();
        pnlMenuBanHang1 = new javax.swing.JPanel();
        lblMenuBanHang1 = new javax.swing.JLabel();
        pnlMenuSanPham1 = new javax.swing.JPanel();
        lblMenuSanPham1 = new javax.swing.JLabel();
        pnlMenuKhuyenMai1 = new javax.swing.JPanel();
        lblMenuKhuyenMai1 = new javax.swing.JLabel();
        pnlMenuHoaDon1 = new javax.swing.JPanel();
        lblMenuHoaDon1 = new javax.swing.JLabel();
        pnlMenuNhanVien1 = new javax.swing.JPanel();
        lblMenuNhanVien1 = new javax.swing.JLabel();
        pnlMenuKhachHang1 = new javax.swing.JPanel();
        lblMenuKhachHang1 = new javax.swing.JLabel();
        pnlMenuThongKe1 = new javax.swing.JPanel();
        lblMenuThongKe1 = new javax.swing.JLabel();
        pnlGiaoDienChinh1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lblClock = new javax.swing.JLabel();
        lblLogo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(219, 184, 142));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pnlMenu1.setBackground(new java.awt.Color(219, 184, 142));

        pnlMenuBanHang1.setBackground(new java.awt.Color(219, 184, 142));
        pnlMenuBanHang1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblMenuBanHang1.setBackground(new java.awt.Color(204, 204, 204));
        lblMenuBanHang1.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        lblMenuBanHang1.setForeground(new java.awt.Color(52, 26, 18));
        lblMenuBanHang1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-sell-25.png"))); // NOI18N
        lblMenuBanHang1.setText("Bán hàng");

        javax.swing.GroupLayout pnlMenuBanHang1Layout = new javax.swing.GroupLayout(pnlMenuBanHang1);
        pnlMenuBanHang1.setLayout(pnlMenuBanHang1Layout);
        pnlMenuBanHang1Layout.setHorizontalGroup(
            pnlMenuBanHang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuBanHang1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuBanHang1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlMenuBanHang1Layout.setVerticalGroup(
            pnlMenuBanHang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuBanHang1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuBanHang1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
        );

        pnlMenuSanPham1.setBackground(new java.awt.Color(219, 184, 142));
        pnlMenuSanPham1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        lblMenuSanPham1.setBackground(new java.awt.Color(204, 204, 204));
        lblMenuSanPham1.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        lblMenuSanPham1.setForeground(new java.awt.Color(52, 26, 18));
        lblMenuSanPham1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-product-25.png"))); // NOI18N
        lblMenuSanPham1.setText("Sản phẩm");

        javax.swing.GroupLayout pnlMenuSanPham1Layout = new javax.swing.GroupLayout(pnlMenuSanPham1);
        pnlMenuSanPham1.setLayout(pnlMenuSanPham1Layout);
        pnlMenuSanPham1Layout.setHorizontalGroup(
            pnlMenuSanPham1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuSanPham1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuSanPham1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlMenuSanPham1Layout.setVerticalGroup(
            pnlMenuSanPham1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuSanPham1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuSanPham1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
        );

        pnlMenuKhuyenMai1.setBackground(new java.awt.Color(219, 184, 142));
        pnlMenuKhuyenMai1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblMenuKhuyenMai1.setBackground(new java.awt.Color(147, 118, 106));
        lblMenuKhuyenMai1.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        lblMenuKhuyenMai1.setForeground(new java.awt.Color(52, 26, 18));
        lblMenuKhuyenMai1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-promotion-25.png"))); // NOI18N
        lblMenuKhuyenMai1.setText("Khuyến mãi");

        javax.swing.GroupLayout pnlMenuKhuyenMai1Layout = new javax.swing.GroupLayout(pnlMenuKhuyenMai1);
        pnlMenuKhuyenMai1.setLayout(pnlMenuKhuyenMai1Layout);
        pnlMenuKhuyenMai1Layout.setHorizontalGroup(
            pnlMenuKhuyenMai1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuKhuyenMai1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMenuKhuyenMai1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlMenuKhuyenMai1Layout.setVerticalGroup(
            pnlMenuKhuyenMai1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuKhuyenMai1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuKhuyenMai1, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlMenuHoaDon1.setBackground(new java.awt.Color(219, 184, 142));
        pnlMenuHoaDon1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblMenuHoaDon1.setBackground(new java.awt.Color(147, 118, 106));
        lblMenuHoaDon1.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        lblMenuHoaDon1.setForeground(new java.awt.Color(52, 26, 18));
        lblMenuHoaDon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-bill-25.png"))); // NOI18N
        lblMenuHoaDon1.setText("Hóa đơn");

        javax.swing.GroupLayout pnlMenuHoaDon1Layout = new javax.swing.GroupLayout(pnlMenuHoaDon1);
        pnlMenuHoaDon1.setLayout(pnlMenuHoaDon1Layout);
        pnlMenuHoaDon1Layout.setHorizontalGroup(
            pnlMenuHoaDon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuHoaDon1Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(lblMenuHoaDon1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlMenuHoaDon1Layout.setVerticalGroup(
            pnlMenuHoaDon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuHoaDon1Layout.createSequentialGroup()
                .addComponent(lblMenuHoaDon1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlMenuNhanVien1.setBackground(new java.awt.Color(219, 184, 142));
        pnlMenuNhanVien1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblMenuNhanVien1.setBackground(new java.awt.Color(147, 118, 106));
        lblMenuNhanVien1.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        lblMenuNhanVien1.setForeground(new java.awt.Color(52, 26, 18));
        lblMenuNhanVien1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-staff-25.png"))); // NOI18N
        lblMenuNhanVien1.setText("Nhân viên");

        javax.swing.GroupLayout pnlMenuNhanVien1Layout = new javax.swing.GroupLayout(pnlMenuNhanVien1);
        pnlMenuNhanVien1.setLayout(pnlMenuNhanVien1Layout);
        pnlMenuNhanVien1Layout.setHorizontalGroup(
            pnlMenuNhanVien1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuNhanVien1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMenuNhanVien1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlMenuNhanVien1Layout.setVerticalGroup(
            pnlMenuNhanVien1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuNhanVien1Layout.createSequentialGroup()
                .addComponent(lblMenuNhanVien1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlMenuKhachHang1.setBackground(new java.awt.Color(219, 184, 142));
        pnlMenuKhachHang1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblMenuKhachHang1.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        lblMenuKhachHang1.setForeground(new java.awt.Color(52, 26, 18));
        lblMenuKhachHang1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-client-25.png"))); // NOI18N
        lblMenuKhachHang1.setText("Khách hàng");

        javax.swing.GroupLayout pnlMenuKhachHang1Layout = new javax.swing.GroupLayout(pnlMenuKhachHang1);
        pnlMenuKhachHang1.setLayout(pnlMenuKhachHang1Layout);
        pnlMenuKhachHang1Layout.setHorizontalGroup(
            pnlMenuKhachHang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuKhachHang1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuKhachHang1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlMenuKhachHang1Layout.setVerticalGroup(
            pnlMenuKhachHang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMenuKhachHang1, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
        );

        pnlMenuThongKe1.setBackground(new java.awt.Color(219, 184, 142));
        pnlMenuThongKe1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblMenuThongKe1.setBackground(new java.awt.Color(204, 204, 204));
        lblMenuThongKe1.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        lblMenuThongKe1.setForeground(new java.awt.Color(52, 26, 18));
        lblMenuThongKe1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-graph-report-script-25.png"))); // NOI18N
        lblMenuThongKe1.setText("Thống kê");

        javax.swing.GroupLayout pnlMenuThongKe1Layout = new javax.swing.GroupLayout(pnlMenuThongKe1);
        pnlMenuThongKe1.setLayout(pnlMenuThongKe1Layout);
        pnlMenuThongKe1Layout.setHorizontalGroup(
            pnlMenuThongKe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuThongKe1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuThongKe1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlMenuThongKe1Layout.setVerticalGroup(
            pnlMenuThongKe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuThongKe1Layout.createSequentialGroup()
                .addComponent(lblMenuThongKe1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlMenu1Layout = new javax.swing.GroupLayout(pnlMenu1);
        pnlMenu1.setLayout(pnlMenu1Layout);
        pnlMenu1Layout.setHorizontalGroup(
            pnlMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenu1Layout.createSequentialGroup()
                .addGroup(pnlMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlMenuBanHang1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMenuSanPham1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMenuKhachHang1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMenuNhanVien1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(pnlMenuHoaDon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMenuKhuyenMai1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMenuThongKe1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlMenu1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {pnlMenuBanHang1, pnlMenuHoaDon1, pnlMenuKhachHang1, pnlMenuKhuyenMai1, pnlMenuNhanVien1, pnlMenuSanPham1});

        pnlMenu1Layout.setVerticalGroup(
            pnlMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenu1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlMenuBanHang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMenuSanPham1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMenuKhuyenMai1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMenuHoaDon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMenuNhanVien1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMenuKhachHang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMenuThongKe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlMenu1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {pnlMenuBanHang1, pnlMenuHoaDon1, pnlMenuKhachHang1, pnlMenuKhuyenMai1, pnlMenuNhanVien1, pnlMenuSanPham1});

        pnlGiaoDienChinh1.setBackground(new java.awt.Color(224, 215, 199));
        pnlGiaoDienChinh1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout pnlGiaoDienChinh1Layout = new javax.swing.GroupLayout(pnlGiaoDienChinh1);
        pnlGiaoDienChinh1.setLayout(pnlGiaoDienChinh1Layout);
        pnlGiaoDienChinh1Layout.setHorizontalGroup(
            pnlGiaoDienChinh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1650, Short.MAX_VALUE)
        );
        pnlGiaoDienChinh1Layout.setVerticalGroup(
            pnlGiaoDienChinh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 733, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(95, 68, 39));

        lblClock.setBackground(new java.awt.Color(204, 0, 51));
        lblClock.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblClock.setForeground(new java.awt.Color(0, 0, 0));
        lblClock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClock.setText("Time");

        lblLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(pnlGiaoDienChinh1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(39, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblClock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addComponent(pnlGiaoDienChinh1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienChinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblLogo1;
    private javax.swing.JLabel lblMenuBanHang1;
    private javax.swing.JLabel lblMenuHoaDon1;
    private javax.swing.JLabel lblMenuKhachHang1;
    private javax.swing.JLabel lblMenuKhuyenMai1;
    private javax.swing.JLabel lblMenuNhanVien1;
    private javax.swing.JLabel lblMenuSanPham1;
    private javax.swing.JLabel lblMenuThongKe1;
    private javax.swing.JPanel pnlGiaoDienChinh1;
    private javax.swing.JPanel pnlMenu1;
    private javax.swing.JPanel pnlMenuBanHang1;
    private javax.swing.JPanel pnlMenuHoaDon1;
    private javax.swing.JPanel pnlMenuKhachHang1;
    private javax.swing.JPanel pnlMenuKhuyenMai1;
    private javax.swing.JPanel pnlMenuNhanVien1;
    private javax.swing.JPanel pnlMenuSanPham1;
    private javax.swing.JPanel pnlMenuThongKe1;
    // End of variables declaration//GEN-END:variables
}
