/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Bean.DanhMucBean;
import Controller.ChuyenGiaoDien;
import java.util.ArrayList;
import java.util.List;
/**
 *
 * @author admin
 */
public class GiaoDienChinh extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public GiaoDienChinh() {
        initComponents();
        
        ChuyenGiaoDien controller = new ChuyenGiaoDien(pnlGiaoDienChinh);
        controller.setView(pnlMenuBanHang, lblMenuBanHang);
        
        List<DanhMucBean> listItem = new ArrayList<>();
        listItem.add(new DanhMucBean("BanHang", pnlMenuBanHang, lblMenuBanHang));
        listItem.add(new DanhMucBean("SanPham", pnlMenuSanPham, lblMenuSanPham));
        listItem.add(new DanhMucBean("KhuyenMai", pnlMenuKhuyenMai, lblMenuKhuyenMai));
        listItem.add(new DanhMucBean("HoaDon", pnlMenuHoaDon, lblMenuHoaDon));
        listItem.add(new DanhMucBean("NhanVien", pnlMenuNhanVien, lblMenuNhanVien));
        listItem.add(new DanhMucBean("KhachHang", pnlMenuKhachHang, lblMenuKhachHang));
        listItem.add(new DanhMucBean("ThongKe", pnlMenuThongKe, lblMenuThongKe));
        
        controller.setEvent(listItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContainer = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        pnlMenuBanHang = new javax.swing.JPanel();
        lblMenuBanHang = new javax.swing.JLabel();
        pnlMenuSanPham = new javax.swing.JPanel();
        lblMenuSanPham = new javax.swing.JLabel();
        pnlMenuKhuyenMai = new javax.swing.JPanel();
        lblMenuKhuyenMai = new javax.swing.JLabel();
        pnlMenuHoaDon = new javax.swing.JPanel();
        lblMenuHoaDon = new javax.swing.JLabel();
        pnlMenuNhanVien = new javax.swing.JPanel();
        lblMenuNhanVien = new javax.swing.JLabel();
        pnlMenuKhachHang = new javax.swing.JPanel();
        lblMenuKhachHang = new javax.swing.JLabel();
        pnlMenuThongKe = new javax.swing.JPanel();
        lblMenuThongKe = new javax.swing.JLabel();
        pnlBody = new javax.swing.JPanel();
        pnlGiaoDienChinh = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlContainer.setLayout(new javax.swing.BoxLayout(pnlContainer, javax.swing.BoxLayout.PAGE_AXIS));

        pnlMenu.setMinimumSize(new java.awt.Dimension(780, 50));
        pnlMenu.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Logo.png"))); // NOI18N
        pnlMenu.add(lblLogo);

        pnlMenuBanHang.setBackground(new java.awt.Color(222, 184, 142));

        lblMenuBanHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMenuBanHang.setForeground(new java.awt.Color(102, 0, 255));
        lblMenuBanHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenuBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-bill-25.png"))); // NOI18N
        lblMenuBanHang.setText("Bán hàng");

        javax.swing.GroupLayout pnlMenuBanHangLayout = new javax.swing.GroupLayout(pnlMenuBanHang);
        pnlMenuBanHang.setLayout(pnlMenuBanHangLayout);
        pnlMenuBanHangLayout.setHorizontalGroup(
            pnlMenuBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuBanHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlMenuBanHangLayout.setVerticalGroup(
            pnlMenuBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuBanHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblMenuBanHang.getAccessibleContext().setAccessibleName("");

        pnlMenu.add(pnlMenuBanHang);

        pnlMenuSanPham.setBackground(new java.awt.Color(222, 184, 142));

        lblMenuSanPham.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMenuSanPham.setForeground(new java.awt.Color(102, 0, 255));
        lblMenuSanPham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenuSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-product-25.png"))); // NOI18N
        lblMenuSanPham.setText("Sản phẩm");

        javax.swing.GroupLayout pnlMenuSanPhamLayout = new javax.swing.GroupLayout(pnlMenuSanPham);
        pnlMenuSanPham.setLayout(pnlMenuSanPhamLayout);
        pnlMenuSanPhamLayout.setHorizontalGroup(
            pnlMenuSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuSanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlMenuSanPhamLayout.setVerticalGroup(
            pnlMenuSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuSanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblMenuSanPham.getAccessibleContext().setAccessibleName("");

        pnlMenu.add(pnlMenuSanPham);

        pnlMenuKhuyenMai.setBackground(new java.awt.Color(222, 184, 142));

        lblMenuKhuyenMai.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMenuKhuyenMai.setForeground(new java.awt.Color(102, 0, 255));
        lblMenuKhuyenMai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenuKhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-promotion-25.png"))); // NOI18N
        lblMenuKhuyenMai.setText("Khuyến mãi");

        javax.swing.GroupLayout pnlMenuKhuyenMaiLayout = new javax.swing.GroupLayout(pnlMenuKhuyenMai);
        pnlMenuKhuyenMai.setLayout(pnlMenuKhuyenMaiLayout);
        pnlMenuKhuyenMaiLayout.setHorizontalGroup(
            pnlMenuKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuKhuyenMaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuKhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlMenuKhuyenMaiLayout.setVerticalGroup(
            pnlMenuKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuKhuyenMaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuKhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblMenuKhuyenMai.getAccessibleContext().setAccessibleName("");

        pnlMenu.add(pnlMenuKhuyenMai);

        pnlMenuHoaDon.setBackground(new java.awt.Color(222, 184, 142));

        lblMenuHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMenuHoaDon.setForeground(new java.awt.Color(102, 0, 255));
        lblMenuHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenuHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-bill-25.png"))); // NOI18N
        lblMenuHoaDon.setText("Hóa đơn");

        javax.swing.GroupLayout pnlMenuHoaDonLayout = new javax.swing.GroupLayout(pnlMenuHoaDon);
        pnlMenuHoaDon.setLayout(pnlMenuHoaDonLayout);
        pnlMenuHoaDonLayout.setHorizontalGroup(
            pnlMenuHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlMenuHoaDonLayout.setVerticalGroup(
            pnlMenuHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblMenuHoaDon.getAccessibleContext().setAccessibleName("");

        pnlMenu.add(pnlMenuHoaDon);

        pnlMenuNhanVien.setBackground(new java.awt.Color(222, 184, 142));

        lblMenuNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMenuNhanVien.setForeground(new java.awt.Color(102, 0, 255));
        lblMenuNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenuNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-staff-25.png"))); // NOI18N
        lblMenuNhanVien.setText("Nhân viên");

        javax.swing.GroupLayout pnlMenuNhanVienLayout = new javax.swing.GroupLayout(pnlMenuNhanVien);
        pnlMenuNhanVien.setLayout(pnlMenuNhanVienLayout);
        pnlMenuNhanVienLayout.setHorizontalGroup(
            pnlMenuNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlMenuNhanVienLayout.setVerticalGroup(
            pnlMenuNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblMenuNhanVien.getAccessibleContext().setAccessibleName("");

        pnlMenu.add(pnlMenuNhanVien);

        pnlMenuKhachHang.setBackground(new java.awt.Color(222, 184, 142));

        lblMenuKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMenuKhachHang.setForeground(new java.awt.Color(102, 0, 255));
        lblMenuKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenuKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-client-25.png"))); // NOI18N
        lblMenuKhachHang.setText("Khách hàng");

        javax.swing.GroupLayout pnlMenuKhachHangLayout = new javax.swing.GroupLayout(pnlMenuKhachHang);
        pnlMenuKhachHang.setLayout(pnlMenuKhachHangLayout);
        pnlMenuKhachHangLayout.setHorizontalGroup(
            pnlMenuKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuKhachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlMenuKhachHangLayout.setVerticalGroup(
            pnlMenuKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuKhachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblMenuKhachHang.getAccessibleContext().setAccessibleName("");

        pnlMenu.add(pnlMenuKhachHang);

        pnlMenuThongKe.setBackground(new java.awt.Color(222, 184, 142));

        lblMenuThongKe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMenuThongKe.setForeground(new java.awt.Color(102, 0, 255));
        lblMenuThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenuThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-graph-report-script-25.png"))); // NOI18N
        lblMenuThongKe.setText("Thống kê");

        javax.swing.GroupLayout pnlMenuThongKeLayout = new javax.swing.GroupLayout(pnlMenuThongKe);
        pnlMenuThongKe.setLayout(pnlMenuThongKeLayout);
        pnlMenuThongKeLayout.setHorizontalGroup(
            pnlMenuThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuThongKeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlMenuThongKeLayout.setVerticalGroup(
            pnlMenuThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuThongKeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblMenuThongKe.getAccessibleContext().setAccessibleName("");

        pnlMenu.add(pnlMenuThongKe);

        pnlContainer.add(pnlMenu);

        pnlBody.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlBody.setLayout(new java.awt.BorderLayout());

        pnlGiaoDienChinh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout pnlGiaoDienChinhLayout = new javax.swing.GroupLayout(pnlGiaoDienChinh);
        pnlGiaoDienChinh.setLayout(pnlGiaoDienChinhLayout);
        pnlGiaoDienChinhLayout.setHorizontalGroup(
            pnlGiaoDienChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1680, Short.MAX_VALUE)
        );
        pnlGiaoDienChinhLayout.setVerticalGroup(
            pnlGiaoDienChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 777, Short.MAX_VALUE)
        );

        pnlBody.add(pnlGiaoDienChinh, java.awt.BorderLayout.CENTER);

        pnlContainer.add(pnlBody);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienChinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMenuBanHang;
    private javax.swing.JLabel lblMenuHoaDon;
    private javax.swing.JLabel lblMenuKhachHang;
    private javax.swing.JLabel lblMenuKhuyenMai;
    private javax.swing.JLabel lblMenuNhanVien;
    private javax.swing.JLabel lblMenuSanPham;
    private javax.swing.JLabel lblMenuThongKe;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlContainer;
    private javax.swing.JPanel pnlGiaoDienChinh;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlMenuBanHang;
    private javax.swing.JPanel pnlMenuHoaDon;
    private javax.swing.JPanel pnlMenuKhachHang;
    private javax.swing.JPanel pnlMenuKhuyenMai;
    private javax.swing.JPanel pnlMenuNhanVien;
    private javax.swing.JPanel pnlMenuSanPham;
    private javax.swing.JPanel pnlMenuThongKe;
    // End of variables declaration//GEN-END:variables
}
