/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Bean.DanhMucBean;
import Controller.ChuyenGiaoDien;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Admin
 */
public class GiaoDienChinh1 extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDienChinh
     */
    public GiaoDienChinh1() {
        ChuyenGiaoDien controller = new ChuyenGiaoDien(pnlGiaoDienChinh);
        controller.setView(pnlMenuBanHang, lblMenuBanHang);
        
        List<DanhMucBean> listItem = new ArrayList<>();
        listItem.add(new DanhMucBean("BanHang", pnlMenuBanHang, lblMenuBanHang));
        listItem.add(new DanhMucBean("SanPham", pnlMenuSanPham, lblMenuSanPham));
        listItem.add(new DanhMucBean("KhuyenMai", pnlMenuKhuyenMai, lblMenuKhuyenMai));
        listItem.add(new DanhMucBean("HoaDon", pnlMenuHoaDon, lblMenuHoaDon));
        listItem.add(new DanhMucBean("NhanVien", pnlMenuNhanVien, lblMenuNhanVien));
        listItem.add(new DanhMucBean("KhachHang", pnlMenuKhachHang, lblMenuKhachHang));
        listItem.add(new DanhMucBean("ThongKe", pnlMenuThongKe, lblMenuThongKe));
        
        controller.setEvent(listItem);
        
        setLocationRelativeTo(null);
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        pnlMenuBanHang = new javax.swing.JPanel();
        lblMenuBanHang = new javax.swing.JLabel();
        pnlMenuSanPham = new javax.swing.JPanel();
        lblMenuSanPham = new javax.swing.JLabel();
        pnlMenuKhuyenMai = new javax.swing.JPanel();
        lblMenuKhuyenMai = new javax.swing.JLabel();
        pnlMenuHoaDon = new javax.swing.JPanel();
        lblMenuHoaDon = new javax.swing.JLabel();
        pnlMenuNhanVien = new javax.swing.JPanel();
        lblMenuNhanVien = new javax.swing.JLabel();
        pnlMenuKhachHang = new javax.swing.JPanel();
        lblMenuKhachHang = new javax.swing.JLabel();
        pnlMenuThongKe = new javax.swing.JPanel();
        lblMenuThongKe = new javax.swing.JLabel();
        pnlGiaoDienChinh = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(219, 184, 142));

        jPanel1.setBackground(new java.awt.Color(219, 184, 142));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pnlMenu.setBackground(new java.awt.Color(219, 184, 142));

        pnlMenuBanHang.setBackground(new java.awt.Color(219, 184, 142));
        pnlMenuBanHang.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblMenuBanHang.setBackground(new java.awt.Color(204, 204, 204));
        lblMenuBanHang.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        lblMenuBanHang.setForeground(new java.awt.Color(52, 26, 18));
        lblMenuBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-sell-25.png"))); // NOI18N
        lblMenuBanHang.setText("Bán hàng");

        javax.swing.GroupLayout pnlMenuBanHangLayout = new javax.swing.GroupLayout(pnlMenuBanHang);
        pnlMenuBanHang.setLayout(pnlMenuBanHangLayout);
        pnlMenuBanHangLayout.setHorizontalGroup(
            pnlMenuBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuBanHangLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblMenuBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMenuBanHangLayout.setVerticalGroup(
            pnlMenuBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuBanHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuBanHang)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pnlMenuSanPham.setBackground(new java.awt.Color(219, 184, 142));
        pnlMenuSanPham.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        lblMenuSanPham.setBackground(new java.awt.Color(204, 204, 204));
        lblMenuSanPham.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        lblMenuSanPham.setForeground(new java.awt.Color(52, 26, 18));
        lblMenuSanPham.setText("Sản phẩm");

        javax.swing.GroupLayout pnlMenuSanPhamLayout = new javax.swing.GroupLayout(pnlMenuSanPham);
        pnlMenuSanPham.setLayout(pnlMenuSanPhamLayout);
        pnlMenuSanPhamLayout.setHorizontalGroup(
            pnlMenuSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuSanPhamLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblMenuSanPham)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMenuSanPhamLayout.setVerticalGroup(
            pnlMenuSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuSanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuSanPham)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pnlMenuKhuyenMai.setBackground(new java.awt.Color(219, 184, 142));
        pnlMenuKhuyenMai.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblMenuKhuyenMai.setBackground(new java.awt.Color(147, 118, 106));
        lblMenuKhuyenMai.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        lblMenuKhuyenMai.setForeground(new java.awt.Color(52, 26, 18));
        lblMenuKhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-promotion-25.png"))); // NOI18N
        lblMenuKhuyenMai.setText("Khuyến mãi");

        javax.swing.GroupLayout pnlMenuKhuyenMaiLayout = new javax.swing.GroupLayout(pnlMenuKhuyenMai);
        pnlMenuKhuyenMai.setLayout(pnlMenuKhuyenMaiLayout);
        pnlMenuKhuyenMaiLayout.setHorizontalGroup(
            pnlMenuKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuKhuyenMaiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMenuKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlMenuKhuyenMaiLayout.setVerticalGroup(
            pnlMenuKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuKhuyenMaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuKhuyenMai)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pnlMenuHoaDon.setBackground(new java.awt.Color(219, 184, 142));
        pnlMenuHoaDon.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblMenuHoaDon.setBackground(new java.awt.Color(147, 118, 106));
        lblMenuHoaDon.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        lblMenuHoaDon.setForeground(new java.awt.Color(52, 26, 18));
        lblMenuHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-bill-25.png"))); // NOI18N
        lblMenuHoaDon.setText("Hóa đơn");

        javax.swing.GroupLayout pnlMenuHoaDonLayout = new javax.swing.GroupLayout(pnlMenuHoaDon);
        pnlMenuHoaDon.setLayout(pnlMenuHoaDonLayout);
        pnlMenuHoaDonLayout.setHorizontalGroup(
            pnlMenuHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuHoaDonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMenuHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        pnlMenuHoaDonLayout.setVerticalGroup(
            pnlMenuHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuHoaDonLayout.createSequentialGroup()
                .addComponent(lblMenuHoaDon)
                .addGap(0, 49, Short.MAX_VALUE))
        );

        pnlMenuNhanVien.setBackground(new java.awt.Color(219, 184, 142));
        pnlMenuNhanVien.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblMenuNhanVien.setBackground(new java.awt.Color(147, 118, 106));
        lblMenuNhanVien.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        lblMenuNhanVien.setForeground(new java.awt.Color(52, 26, 18));
        lblMenuNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-staff-25.png"))); // NOI18N
        lblMenuNhanVien.setText("Nhân viên");

        javax.swing.GroupLayout pnlMenuNhanVienLayout = new javax.swing.GroupLayout(pnlMenuNhanVien);
        pnlMenuNhanVien.setLayout(pnlMenuNhanVienLayout);
        pnlMenuNhanVienLayout.setHorizontalGroup(
            pnlMenuNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuNhanVienLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMenuNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        pnlMenuNhanVienLayout.setVerticalGroup(
            pnlMenuNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuNhanVienLayout.createSequentialGroup()
                .addComponent(lblMenuNhanVien)
                .addGap(0, 49, Short.MAX_VALUE))
        );

        pnlMenuKhachHang.setBackground(new java.awt.Color(219, 184, 142));
        pnlMenuKhachHang.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblMenuKhachHang.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        lblMenuKhachHang.setForeground(new java.awt.Color(52, 26, 18));
        lblMenuKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-client-25.png"))); // NOI18N
        lblMenuKhachHang.setText("Khách hàng");

        javax.swing.GroupLayout pnlMenuKhachHangLayout = new javax.swing.GroupLayout(pnlMenuKhachHang);
        pnlMenuKhachHang.setLayout(pnlMenuKhachHangLayout);
        pnlMenuKhachHangLayout.setHorizontalGroup(
            pnlMenuKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuKhachHangLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblMenuKhachHang)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMenuKhachHangLayout.setVerticalGroup(
            pnlMenuKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuKhachHangLayout.createSequentialGroup()
                .addComponent(lblMenuKhachHang)
                .addGap(0, 49, Short.MAX_VALUE))
        );

        pnlMenuThongKe.setBackground(new java.awt.Color(219, 184, 142));
        pnlMenuThongKe.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblMenuThongKe.setBackground(new java.awt.Color(204, 204, 204));
        lblMenuThongKe.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        lblMenuThongKe.setForeground(new java.awt.Color(52, 26, 18));
        lblMenuThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-graph-report-script-25.png"))); // NOI18N
        lblMenuThongKe.setText("Thống kê");

        javax.swing.GroupLayout pnlMenuThongKeLayout = new javax.swing.GroupLayout(pnlMenuThongKe);
        pnlMenuThongKe.setLayout(pnlMenuThongKeLayout);
        pnlMenuThongKeLayout.setHorizontalGroup(
            pnlMenuThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuThongKeLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(lblMenuThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        pnlMenuThongKeLayout.setVerticalGroup(
            pnlMenuThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuThongKeLayout.createSequentialGroup()
                .addComponent(lblMenuThongKe)
                .addGap(0, 49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenuBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMenuSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMenuKhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMenuHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMenuNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMenuKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMenuThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMenuBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMenuSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMenuKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMenuHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMenuNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMenuKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMenuThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMenuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {pnlMenuBanHang, pnlMenuHoaDon, pnlMenuKhachHang, pnlMenuKhuyenMai, pnlMenuNhanVien, pnlMenuSanPham, pnlMenuThongKe});

        pnlGiaoDienChinh.setBackground(new java.awt.Color(224, 215, 199));
        pnlGiaoDienChinh.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout pnlGiaoDienChinhLayout = new javax.swing.GroupLayout(pnlGiaoDienChinh);
        pnlGiaoDienChinh.setLayout(pnlGiaoDienChinhLayout);
        pnlGiaoDienChinhLayout.setHorizontalGroup(
            pnlGiaoDienChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1290, Short.MAX_VALUE)
        );
        pnlGiaoDienChinhLayout.setVerticalGroup(
            pnlGiaoDienChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 755, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(95, 68, 39));

        jLabel1.setText("jLabel1");

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(pnlGiaoDienChinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlGiaoDienChinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienChinh1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMenuBanHang;
    private javax.swing.JLabel lblMenuHoaDon;
    private javax.swing.JLabel lblMenuKhachHang;
    private javax.swing.JLabel lblMenuKhuyenMai;
    private javax.swing.JLabel lblMenuNhanVien;
    private javax.swing.JLabel lblMenuSanPham;
    private javax.swing.JLabel lblMenuThongKe;
    private javax.swing.JPanel pnlGiaoDienChinh;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlMenuBanHang;
    private javax.swing.JPanel pnlMenuHoaDon;
    private javax.swing.JPanel pnlMenuKhachHang;
    private javax.swing.JPanel pnlMenuKhuyenMai;
    private javax.swing.JPanel pnlMenuNhanVien;
    private javax.swing.JPanel pnlMenuSanPham;
    private javax.swing.JPanel pnlMenuThongKe;
    // End of variables declaration//GEN-END:variables
}
