/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.KhachHangModel.KhachHang;

import Repository.RepoKhachHang;
import java.awt.Color;
//import java.text.ParseException;
//import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
//import java.util.logging.Level;
//import java.util.logging.Logger;/
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class ViewKhachHang1 extends javax.swing.JPanel {

    /**
     * Creates new form ViewKhachHang
     */
    private Repository.RepoKhachHang rp = new RepoKhachHang();
    private DefaultTableModel mol = new DefaultTableModel();
    private int index = -1;

    public ViewKhachHang1() {
        initComponents();

        rdo_htt_AllGT.setSelected(true);
        rdo_htt_AllTT.setSelected(true);

        hienThiBang();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        rdoGroupTinhTrangKH = new javax.swing.ButtonGroup();
        jPanel13 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btn_hht_hienthi = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        radio_htt_nam = new javax.swing.JRadioButton();
        radio_htt_nu = new javax.swing.JRadioButton();
        rdo_htt_AllGT = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        radio_htt_khonghoatdong = new javax.swing.JRadioButton();
        radio_htt_hoatdong = new javax.swing.JRadioButton();
        rdo_htt_AllTT = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btn_htt_lammoi = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btn_tk_tim = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txt_tk_SDtKH = new javax.swing.JTextField();
        txt_tk_makh = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btn_tk_lammoi = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_khachHang = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNamSinh = new javax.swing.JTextField();
        pan_tt_gioiTinh = new javax.swing.JPanel();
        radio_TT_Nam = new javax.swing.JRadioButton();
        radio_TT_nu = new javax.swing.JRadioButton();
        radio_TT_khac = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txt_tt_Diachikhachhang = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        radio_tt_hoatdong = new javax.swing.JRadioButton();
        radio_TT_khonghoatdong = new javax.swing.JRadioButton();
        txt_tt_Makhachhang = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_tt_Mailkhachhang = new javax.swing.JTextField();
        txt_tt_Tenkhachhang = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_tt_SDTkhachhang = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_tt_lammoi = new javax.swing.JButton();
        btn_tt_them = new javax.swing.JButton();
        btn_tt_sua = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1700, 850));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_hht_hienthi.setText("Hiên Thị");
        btn_hht_hienthi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hht_hienthiActionPerformed(evt);
            }
        });

        buttonGroup2.add(radio_htt_nam);
        radio_htt_nam.setText("Nam");

        buttonGroup2.add(radio_htt_nu);
        radio_htt_nu.setText("Nữ");

        buttonGroup2.add(rdo_htt_AllGT);
        rdo_htt_AllGT.setSelected(true);
        rdo_htt_AllGT.setText("All");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(rdo_htt_AllGT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radio_htt_nam)
                .addGap(18, 18, 18)
                .addComponent(radio_htt_nu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio_htt_nam)
                    .addComponent(radio_htt_nu)
                    .addComponent(rdo_htt_AllGT))
                .addGap(0, 0, 0))
        );

        buttonGroup1.add(radio_htt_khonghoatdong);
        radio_htt_khonghoatdong.setText("Không hoạt động");

        buttonGroup1.add(radio_htt_hoatdong);
        radio_htt_hoatdong.setText("Đang hoạt động");

        buttonGroup1.add(rdo_htt_AllTT);
        rdo_htt_AllTT.setSelected(true);
        rdo_htt_AllTT.setText("All");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(rdo_htt_AllTT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radio_htt_hoatdong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radio_htt_khonghoatdong))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio_htt_hoatdong)
                    .addComponent(radio_htt_khonghoatdong)
                    .addComponent(rdo_htt_AllTT))
                .addContainerGap())
        );

        jLabel15.setText("Tình trạng :");

        jLabel16.setText("Giới Tính :");

        btn_htt_lammoi.setText("Làm mới");
        btn_htt_lammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_htt_lammoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btn_hht_hienthi)
                        .addGap(70, 70, 70)
                        .addComponent(btn_htt_lammoi)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_hht_hienthi)
                    .addComponent(btn_htt_lammoi))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel15))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel14.setText("Hiên thị Theo");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel14)
                        .addGap(136, 136, 136))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel13.add(jPanel11);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_tk_tim.setText("Tìm");
        btn_tk_tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tk_timActionPerformed(evt);
            }
        });

        jLabel12.setText("Mã KH :");

        jLabel13.setText("SDT :");

        btn_tk_lammoi.setText("Làm mới");
        btn_tk_lammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tk_lammoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btn_tk_tim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(btn_tk_lammoi)
                        .addGap(12, 12, 12))
                    .addComponent(txt_tk_makh)
                    .addComponent(txt_tk_SDtKH))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_tk_makh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_tk_SDtKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tk_tim)
                    .addComponent(btn_tk_lammoi))
                .addGap(24, 24, 24))
        );

        jLabel11.setText("Tím kiếm");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel13.add(jPanel12);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1000, 350));

        tbl_khachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Khách Hàng", "Họ Và Tên", "Giới Tính", "Năm sinh", "Số Điện Thoại", "Mail", "Đia Chỉ", "Ngày Tạo", "Ngày sửa", "Tình trạng"
            }
        ));
        tbl_khachHang.setMaximumSize(new java.awt.Dimension(2147483647, 450));
        tbl_khachHang.setRowHeight(30);
        tbl_khachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_khachHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_khachHang);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Mã KH       :");

        jLabel4.setText("Giới Tính : ");

        buttonGroup3.add(radio_TT_Nam);
        radio_TT_Nam.setSelected(true);
        radio_TT_Nam.setText("Nam");

        buttonGroup3.add(radio_TT_nu);
        radio_TT_nu.setText("Nữ");

        buttonGroup3.add(radio_TT_khac);
        radio_TT_khac.setText("khác");

        javax.swing.GroupLayout pan_tt_gioiTinhLayout = new javax.swing.GroupLayout(pan_tt_gioiTinh);
        pan_tt_gioiTinh.setLayout(pan_tt_gioiTinhLayout);
        pan_tt_gioiTinhLayout.setHorizontalGroup(
            pan_tt_gioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_tt_gioiTinhLayout.createSequentialGroup()
                .addComponent(radio_TT_Nam)
                .addGap(18, 18, 18)
                .addComponent(radio_TT_nu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(radio_TT_khac, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pan_tt_gioiTinhLayout.setVerticalGroup(
            pan_tt_gioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_tt_gioiTinhLayout.createSequentialGroup()
                .addGroup(pan_tt_gioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio_TT_Nam)
                    .addComponent(radio_TT_nu)
                    .addComponent(radio_TT_khac))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Thông Tin khách hàng");

        txt_tt_Diachikhachhang.setColumns(20);
        txt_tt_Diachikhachhang.setRows(5);

        jLabel10.setText("Tình Trạng :");

        jLabel3.setText("Tên KH      :");

        rdoGroupTinhTrangKH.add(radio_tt_hoatdong);
        radio_tt_hoatdong.setText("Đang hoạt động");

        rdoGroupTinhTrangKH.add(radio_TT_khonghoatdong);
        radio_TT_khonghoatdong.setText("Ngừng hoạt động");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radio_tt_hoatdong)
                .addGap(18, 18, 18)
                .addComponent(radio_TT_khonghoatdong)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(radio_tt_hoatdong)
                .addComponent(radio_TT_khonghoatdong))
        );

        jLabel8.setText("Địa chỉ    :");

        jLabel6.setText("Mail      :");

        jLabel7.setText("Năm sinh :");

        txt_tt_SDTkhachhang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_tt_SDTkhachhangKeyTyped(evt);
            }
        });

        jLabel5.setText("SDT       :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(txt_tt_Tenkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(txt_tt_Makhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pan_tt_gioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_tt_SDTkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel7))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtNamSinh, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_tt_Diachikhachhang, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_tt_Mailkhachhang)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(31, 31, 31))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_tt_Tenkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txt_tt_Diachikhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_tt_Makhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(txtNamSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pan_tt_gioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tt_Mailkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txt_tt_SDTkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel8.add(jPanel4);

        btn_tt_lammoi.setText("Làm mới");
        btn_tt_lammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tt_lammoiActionPerformed(evt);
            }
        });

        btn_tt_them.setText("Thêm");
        btn_tt_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tt_themActionPerformed(evt);
            }
        });

        btn_tt_sua.setText("Sửa");
        btn_tt_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tt_suaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_tt_lammoi)
                    .addComponent(btn_tt_sua)
                    .addComponent(btn_tt_them))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_tt_lammoi, btn_tt_sua, btn_tt_them});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_tt_them)
                .addGap(21, 21, 21)
                .addComponent(btn_tt_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_tt_lammoi)
                .addContainerGap())
        );

        jPanel8.add(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1287, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
void fillTable(ArrayList<KhachHang> list) {
        mol = (DefaultTableModel) tbl_khachHang.getModel();
        mol.setRowCount(0);

        for (KhachHang x : list){
            mol.addRow(x.todatarow());
        }
    }

    void hienThiBang() {
        ArrayList<KhachHang> list = null; // Biến tạm để lưu kết quả trả về từ getAllKhachHang()

        if (rdo_htt_AllGT.isSelected() && rdo_htt_AllTT.isSelected()) {
            list = rp.getAllKhachHang(null, null);
        } else if (rdo_htt_AllGT.isSelected() && radio_htt_hoatdong.isSelected()) {
            list = rp.getAllKhachHang(true, null);
        } else if (rdo_htt_AllGT.isSelected() && radio_htt_khonghoatdong.isSelected()) {
            list = rp.getAllKhachHang(false, null);
        } else if (radio_htt_nam.isSelected() && rdo_htt_AllTT.isSelected()) {
            list = rp.getAllKhachHang(null, true);
        } else if (radio_htt_nu.isSelected() && rdo_htt_AllTT.isSelected()) {
            list = rp.getAllKhachHang(null, false);
        } else if (radio_htt_nu.isSelected() && radio_htt_hoatdong.isSelected()) {
            list = rp.getAllKhachHang(true, false);
        } else if (radio_htt_nu.isSelected() && radio_htt_khonghoatdong.isSelected()) {
            list = rp.getAllKhachHang(false, false);
        }

        // Kiểm tra danh sách trả về
        if (list == null || list.isEmpty()) {
            fillTable(rp.getAllKhachHang(null, null));
            rdo_htt_AllGT.setSelected(true);
            rdo_htt_AllTT.setSelected(true);
            showData(0);
            JOptionPane.showMessageDialog(null, "Không có dữ liệu phù hợp!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return; // Thoát khỏi phương thức nếu không có dữ liệu
        }

        // Hiển thị danh sách trong bảng nếu có dữ liệu
        fillTable(list);
        showData(0);
    }

    void showData(int i) {
        String maKH, hote, namSinh, gt, sdt, mail, ngayTao, diaChi = null;
        boolean tinhTrang;

        maKH = tbl_khachHang.getValueAt(i, 0).toString();
        hote = tbl_khachHang.getValueAt(i, 1).toString();
        gt = tbl_khachHang.getValueAt(i, 2).toString();
        namSinh = tbl_khachHang.getValueAt(i, 3).toString();
        sdt = tbl_khachHang.getValueAt(i, 4).toString();
        mail = tbl_khachHang.getValueAt(i, 5).toString();
        diaChi = tbl_khachHang.getValueAt(i, 6).toString();
        ngayTao = tbl_khachHang.getValueAt(i, 7).toString();
        tinhTrang = rp.getKhachHangByMakh(maKH).isTinhTrang();

        if (gt.equalsIgnoreCase("nam")) {
            radio_TT_Nam.setSelected(true);
        } else if(gt.equalsIgnoreCase("nu")){
            radio_TT_nu.setSelected(true);
        }else{
                radio_TT_khac.setSelected(true);
                }

        if (tinhTrang) {
            radio_tt_hoatdong.setSelected(true);
        } else {
            radio_TT_khonghoatdong.setSelected(true);
        }

        txtNamSinh.setText(tbl_khachHang.getValueAt(i, 3).toString());

        txt_tt_Makhachhang.setText(maKH);
        txt_tt_Tenkhachhang.setText(hote);
        txt_tt_SDTkhachhang.setText(sdt);
        txt_tt_Mailkhachhang.setText(mail);
        txt_tt_Diachikhachhang.setText(diaChi);

        tbl_khachHang.setRowSelectionInterval(i, i);
    }

    void lamMoi() {
        // cchưa xoa được chon radio
        txt_tt_Makhachhang.setText(null);
        txt_tt_Tenkhachhang.setText(null);
        txt_tt_SDTkhachhang.setText(null);
        txt_tt_Mailkhachhang.setText(null);
        txt_tt_Diachikhachhang.setText(null);
        txtNamSinh.setText(null);
        radio_TT_Nam.setSelected(true);;

        txt_tt_Diachikhachhang.setBackground(Color.WHITE);
        txt_tt_Tenkhachhang.setBackground(Color.WHITE);
        txt_tt_SDTkhachhang.setBackground(Color.WHITE);
        txt_tt_Mailkhachhang.setBackground(Color.WHITE);
        txt_tt_Diachikhachhang.setBackground(Color.WHITE);
        txtNamSinh.setBackground(Color.WHITE);
    }

   KhachHang readForm() {
    String maKH = txt_tt_Makhachhang.getText().trim();
    String hoTen = txt_tt_Tenkhachhang.getText().trim();
    String SDT = txt_tt_SDTkhachhang.getText().trim();
    String mail = txt_tt_Mailkhachhang.getText().trim();
    String diaChi = txt_tt_Diachikhachhang.getText().trim();
    
    Date ngayTao = new Date();
    int namSinh = 0;
    try {
        namSinh = Integer.parseInt(txtNamSinh.getText().trim());
    } catch (NumberFormatException e) {
        namSinh = 0; // Đặt giá trị mặc định nếu không chuyển đổi được
    }

    boolean gt = radio_TT_Nam.isSelected();
    boolean tinhTrang = radio_tt_hoatdong.isSelected();
    
    // Kiểm tra email
    String emailPattern = "^[a-zA-Z0-9._%+-]{6,}@[a-zA-Z0-9.-]{2,}\\.[a-zA-Z]{1,}$";
    if (!mail.matches(emailPattern)) {
        JOptionPane.showMessageDialog(this, "Email không hợp lệ. Vui lòng nhập đúng định dạng!");
        txt_tt_Mailkhachhang.setBackground(Color.PINK); // Đổi màu nền thành hồng
        return null;  // Nếu email không hợp lệ, trả về null
    } else {
        txt_tt_Mailkhachhang.setBackground(Color.WHITE); // Khôi phục lại màu nền
    }

    return new KhachHang(maKH, hoTen, gt, namSinh, SDT, mail, diaChi, ngayTao, tinhTrang);
}



    // check số điện thoại
    // chưa check trùng
    boolean checkkhithem_SDT() {
        String sdt = txt_tt_SDTkhachhang.getText().trim();

        // Kiểm tra số điện thoại có trống không
        if (sdt.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập số điện thoại.");
            txt_tt_SDTkhachhang.setBackground(Color.YELLOW);
            return false;
        }

        // Kiểm tra số điện thoại bắt đầu bằng 0 và có đúng 10 chữ số
        if (!sdt.matches("^0[0-9]{9}$")) {
            JOptionPane.showMessageDialog(this, "Số điện thoại phải bắt đầu bằng số 0, có đúng 10 chữ số và không chứa kí tự đặc biệt.");
            txt_tt_SDTkhachhang.setBackground(Color.PINK);
            return false;
        }

        // Kiểm tra trùng số điện thoại trong danh sách
        // Số điện thoại hợp lệ
        txt_tt_SDTkhachhang.setBackground(Color.WHITE);
        return true;
    }


    private void btn_tk_timActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tk_timActionPerformed
        // TODO add your handling code here:
        String sdtCanTim = txt_tk_SDtKH.getText().toString().trim();

        String maKhCanTim = txt_tk_makh.getText().toString().trim();

        if (sdtCanTim.isEmpty() && maKhCanTim.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập thông tin cần tìm");
            if (sdtCanTim.isEmpty()) {
                txt_tk_SDtKH.setBackground(Color.YELLOW);
            }
            if (maKhCanTim.isEmpty()) {
                txt_tk_makh.setBackground(Color.YELLOW);
            }
        } else {
            txt_tk_SDtKH.setBackground(Color.WHITE);
            txt_tk_makh.setBackground(Color.WHITE);
            if (!rp.timSDT(sdtCanTim, maKhCanTim).isEmpty()) {
                fillTable(rp.timSDT(sdtCanTim, maKhCanTim));

            } else {
                JOptionPane.showMessageDialog(this, "Không có khách hàng nào");

            }
        }
    }//GEN-LAST:event_btn_tk_timActionPerformed

    private void btn_tk_lammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tk_lammoiActionPerformed
        // TODO add your handling code here:
        txt_tk_makh.setText(null);
        txt_tk_SDtKH.setText(null);

        fillTable(rp.getAllKhachHang(null, null));

        txt_tk_SDtKH.setBackground(Color.WHITE);
        txt_tk_makh.setBackground(Color.WHITE);
    }//GEN-LAST:event_btn_tk_lammoiActionPerformed

    private void btn_hht_hienthiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hht_hienthiActionPerformed
        hienThiBang();
    }//GEN-LAST:event_btn_hht_hienthiActionPerformed

    private void btn_htt_lammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_htt_lammoiActionPerformed
        rdo_htt_AllGT.setSelected(true);
        rdo_htt_AllTT.setSelected(true);

        hienThiBang();
    }//GEN-LAST:event_btn_htt_lammoiActionPerformed

    private void tbl_khachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_khachHangMouseClicked
        // TODO add your handling code here:
        int index = tbl_khachHang.getSelectedRow();
        showData(index);
    }//GEN-LAST:event_tbl_khachHangMouseClicked

    private void btn_tt_lammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tt_lammoiActionPerformed
        // TODO add your handling code here:
        lamMoi();
    }//GEN-LAST:event_btn_tt_lammoiActionPerformed

    private void btn_tt_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tt_themActionPerformed
        // TODO add your handling code here:y
     if (readForm() != null) {
        KhachHang kh = readForm();
        String sdt = kh.getSoDT();
        String email = kh.getMail();
        String hoTen = kh.getHoTen();
        int namSinh = kh.getNamSinh();
        String maKh = kh.getMakh();

        // Kiểm tra mã khách hàng không được trống
        if (maKh.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mã khách hàng không được để trống.");
            txt_tt_Makhachhang.setBackground(Color.PINK); // Đổi màu nền thành hồng cho mã khách hàng
            return;
        } else {
            txt_tt_Makhachhang.setBackground(Color.WHITE); // Khôi phục lại màu nền nếu hợp lệ
        }

        // Kiểm tra số điện thoại hợp lệ (10 chữ số, bắt đầu bằng 0 và không có ký tự đặc biệt)
        if (sdt.isEmpty() || !sdt.matches("^0[0-9]{9}$")) {
            JOptionPane.showMessageDialog(this, "Số điện thoại phải là 10 chữ số và bắt đầu bằng 0.");
            txt_tt_SDTkhachhang.setBackground(Color.PINK); // Đổi màu nền thành hồng
            return; // Nếu số điện thoại không hợp lệ, dừng lại
        } else {
            txt_tt_SDTkhachhang.setBackground(Color.WHITE); // Khôi phục lại màu nền nếu hợp lệ
        }

        // Kiểm tra tên khách hàng không rỗng
        if (hoTen.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Họ tên không được để trống.");
            txt_tt_Tenkhachhang.setBackground(Color.PINK); // Đổi màu nền thành hồng
            return;
        } else {
            txt_tt_Tenkhachhang.setBackground(Color.WHITE); // Khôi phục lại màu nền nếu hợp lệ
        }

        // Kiểm tra năm sinh hợp lệ
        if (namSinh < 1900 || namSinh > 2020) {
            JOptionPane.showMessageDialog(this, "Năm sinh phải trong khoảng từ 1800 đến 2020.");
            txtNamSinh.setBackground(Color.PINK); // Đổi màu nền thành hồng
            return;
        } else {
            txtNamSinh.setBackground(Color.WHITE); // Khôi phục lại màu nền nếu hợp lệ
        }

        // Kiểm tra email hợp lệ
        String emailPattern = "^[a-zA-Z0-9._%+-]{6,}@[a-zA-Z0-9.-]{2,}\\.[a-zA-Z]{1,}$";
        if (!email.matches(emailPattern)) {
            JOptionPane.showMessageDialog(this, "Email không hợp lệ. Vui lòng nhập đúng định dạng!");
            txt_tt_Mailkhachhang.setBackground(Color.PINK); // Đổi màu nền thành hồng
            return;
        } else {
            txt_tt_Mailkhachhang.setBackground(Color.WHITE); // Khôi phục lại màu nền nếu hợp lệ
        }

        // Kiểm tra trùng số điện thoại, email, tên và mã trong danh sách khách hàng
        boolean isSdtTrung = false;
        boolean isEmailTrung = false;
        boolean isHoTenTrung = false;
        boolean isMaKhTrung = false;

        // Duyệt qua danh sách khách hàng hiện tại để kiểm tra trùng số điện thoại, email, tên và mã
        for (KhachHang existingKh : rp.getAllKhachHang(null, null)) {
            if (existingKh.getSoDT().equals(sdt)) {
                isSdtTrung = true;
            }
            if (existingKh.getMail().equals(email)) {
                isEmailTrung = true;
            }
            if (existingKh.getMakh().equals(maKh)) {
                isMaKhTrung = true;
            }
        }

        // Thông báo nếu có trùng
        if (isSdtTrung) {
            JOptionPane.showMessageDialog(this, "Số điện thoại đã tồn tại.");
            txt_tt_SDTkhachhang.setBackground(Color.PINK); // Đổi màu nền thành hồng
            return;
        }

        if (isEmailTrung) {
            JOptionPane.showMessageDialog(this, "Email đã tồn tại.");
            txt_tt_Mailkhachhang.setBackground(Color.PINK); // Đổi màu nền thành hồng
            return;
        }

        if (isMaKhTrung) {
            JOptionPane.showMessageDialog(this, "Mã khách hàng đã tồn tại.");
            txt_tt_Makhachhang.setBackground(Color.PINK); // Đổi màu nền thành hồng
            return;
        }

        // Tiến hành thêm khách hàng nếu tất cả dữ liệu hợp lệ và không trùng
        int chon = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm khách hàng không?");
        if (chon == 0) {
            try {
                rp.themKhachHang(kh); // Thêm khách hàng vào hệ thống
                JOptionPane.showMessageDialog(this, "Thêm khách hàng thành công!");
                fillTable(rp.getAllKhachHang(null, null)); // Cập nhật lại bảng
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Không thể thêm khách hàng vì lỗi: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Bạn đã hủy việc thêm khách hàng.");
        }
    }

    }//GEN-LAST:event_btn_tt_themActionPerformed

    private void btn_tt_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tt_suaActionPerformed
        // TODO add your handling code here:
        // Lấy chỉ số dòng khách hàng được chọn
        // Lấy chỉ số dòng khách hàng được chọn
    int i = tbl_khachHang.getSelectedRow();

    if (i < 0) {
        // Nếu không chọn dòng nào
        JOptionPane.showMessageDialog(this, "Bạn chưa chọn dòng để sửa");
    } else {
        // Xác nhận việc sửa
        int chon = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn sửa không?");
        if (chon == 0) {
            String maKh = tbl_khachHang.getValueAt(i, 0).toString();

             // Kiểm tra Mã khách hàng không được trống
            if (maKh.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Mã khách hàng không được để trống.");
                tbl_khachHang.setBackground(Color.PINK); // Đổi màu nền thành hồng cho bảng (hoặc trường mã khách hàng nếu là JTextField)
                return;
            } else {
                tbl_khachHang.setBackground(Color.WHITE); // Khôi phục lại màu nền nếu hợp lệ
            }
            
            // Lấy thông tin từ form
            KhachHang kh = readForm();

            if (kh == null) {
                // Nếu readForm trả về null (khi có lỗi trong kiểm tra)
                return;
            }

            String sdt = kh.getSoDT();
            String email = kh.getMail();
            String hoTen = kh.getHoTen();
            int namSinh = kh.getNamSinh();

            // Kiểm tra Số điện thoại hợp lệ (10 chữ số, bắt đầu bằng 0 và không có ký tự đặc biệt)
            if (sdt.isEmpty() || !sdt.matches("^0[0-9]{9}$")) {
                JOptionPane.showMessageDialog(this, "Số điện thoại phải là 10 chữ số và bắt đầu bằng 0.");
                txt_tt_SDTkhachhang.setBackground(Color.PINK); // Đổi màu nền thành hồng
                return; // Nếu số điện thoại không hợp lệ, dừng lại
            } else {
                txt_tt_SDTkhachhang.setBackground(Color.WHITE); // Khôi phục lại màu nền nếu hợp lệ
            }

            // Kiểm tra tên khách hàng không rỗng
            if (hoTen.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Họ tên không được để trống.");
                txt_tt_Tenkhachhang.setBackground(Color.PINK); // Đổi màu nền thành hồng
                return;
            } else {
                txt_tt_Tenkhachhang.setBackground(Color.WHITE); // Khôi phục lại màu nền nếu hợp lệ
            }

            // Kiểm tra năm sinh hợp lệ
            if (namSinh < 1950 || namSinh > 2010) {
                JOptionPane.showMessageDialog(this, "Năm sinh không được bỏ trống và năm sinh phải trong khoảng từ 1950 đến 2010.");
                txtNamSinh.setBackground(Color.PINK); // Đổi màu nền thành hồng
                return;
            } else {
                txtNamSinh.setBackground(Color.WHITE); // Khôi phục lại màu nền nếu hợp lệ
            }

            // Kiểm tra email hợp lệ
            String emailPattern = "^[a-zA-Z0-9._%+-]{6,}@[a-zA-Z0-9.-]{2,}\\.[a-zA-Z]{1,}$";
            if (!email.matches(emailPattern)) {
                JOptionPane.showMessageDialog(this, "Email không hợp lệ. Vui lòng nhập đúng định dạng!");
                txt_tt_Mailkhachhang.setBackground(Color.PINK); // Đổi màu nền thành hồng
                return;
            } else {
                txt_tt_Mailkhachhang.setBackground(Color.WHITE); // Khôi phục lại màu nền nếu hợp lệ
            }

            // Tiến hành sửa thông tin khách hàng
            rp.suaThongTinKH(maKh, kh);
            JOptionPane.showMessageDialog(this, "Sửa thông tin thành công");

            // Cập nhật lại bảng
            this.fillTable(rp.getAllKhachHang(null, null));
            showData(i); // Hiển thị lại dữ liệu mới cho dòng đã chọn
        } else {
            JOptionPane.showMessageDialog(this, "Bạn đã hủy sửa");
        }
    }
    }//GEN-LAST:event_btn_tt_suaActionPerformed

    private void txt_tt_SDTkhachhangKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tt_SDTkhachhangKeyTyped
        if (txt_tk_SDtKH.getText().length() >= 10) {
            evt.consume(); // Ngăn không cho nhập thêm
        }
    }//GEN-LAST:event_txt_tt_SDTkhachhangKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hht_hienthi;
    private javax.swing.JButton btn_htt_lammoi;
    private javax.swing.JButton btn_tk_lammoi;
    private javax.swing.JButton btn_tk_tim;
    private javax.swing.JButton btn_tt_lammoi;
    private javax.swing.JButton btn_tt_sua;
    private javax.swing.JButton btn_tt_them;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pan_tt_gioiTinh;
    private javax.swing.JRadioButton radio_TT_Nam;
    private javax.swing.JRadioButton radio_TT_khac;
    private javax.swing.JRadioButton radio_TT_khonghoatdong;
    private javax.swing.JRadioButton radio_TT_nu;
    private javax.swing.JRadioButton radio_htt_hoatdong;
    private javax.swing.JRadioButton radio_htt_khonghoatdong;
    private javax.swing.JRadioButton radio_htt_nam;
    private javax.swing.JRadioButton radio_htt_nu;
    private javax.swing.JRadioButton radio_tt_hoatdong;
    private javax.swing.ButtonGroup rdoGroupTinhTrangKH;
    private javax.swing.JRadioButton rdo_htt_AllGT;
    private javax.swing.JRadioButton rdo_htt_AllTT;
    private javax.swing.JTable tbl_khachHang;
    private javax.swing.JTextField txtNamSinh;
    private javax.swing.JTextField txt_tk_SDtKH;
    private javax.swing.JTextField txt_tk_makh;
    private javax.swing.JTextArea txt_tt_Diachikhachhang;
    private javax.swing.JTextField txt_tt_Mailkhachhang;
    private javax.swing.JTextField txt_tt_Makhachhang;
    private javax.swing.JTextField txt_tt_SDTkhachhang;
    private javax.swing.JTextField txt_tt_Tenkhachhang;
    // End of variables declaration//GEN-END:variables
}
