/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * @author admin
 */
public class ViewBanHangTest extends javax.swing.JPanel {

    /**
     * Creates new form ViewBanHangTest
     */
    public ViewBanHangTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnl_BanHang = new javax.swing.JPanel();
        pnl_BanHang_Ban = new javax.swing.JPanel();
        pnl_Ban_Ban = new javax.swing.JPanel();
        pnl_Ban_LBL = new javax.swing.JPanel();
        lbl_Ban_LBL = new javax.swing.JLabel();
        pnl_Ban_View = new javax.swing.JPanel();
        jPanel40 = new javax.swing.JPanel();
        jPanel41 = new javax.swing.JPanel();
        jPanel42 = new javax.swing.JPanel();
        jPanel43 = new javax.swing.JPanel();
        jPanel44 = new javax.swing.JPanel();
        pnl_Ban_GiaoHang = new javax.swing.JPanel();
        pnl_GiaoHang_LBL = new javax.swing.JPanel();
        lbl_GiaoHang_LBL = new javax.swing.JLabel();
        pnl_GiaoHang_View = new javax.swing.JPanel();
        jPanel52 = new javax.swing.JPanel();
        jPanel53 = new javax.swing.JPanel();
        jPanel54 = new javax.swing.JPanel();
        jPanel55 = new javax.swing.JPanel();
        jPanel56 = new javax.swing.JPanel();
        pnl_BanHang_HoaDon = new javax.swing.JPanel();
        pnl_HoaDon_SanPham = new javax.swing.JPanel();
        pnl_HoaDon_SanPham_SearchAndAdd = new javax.swing.JPanel();
        lbl_HoaDon_SanPham_LBL = new javax.swing.JLabel();
        pnl_SanPham_SearchAndAdd = new javax.swing.JPanel();
        lbl_SanPham_SearchAndAdd_Search = new javax.swing.JLabel();
        txt_SanPham_SearchAndAdd_Search = new javax.swing.JTextField();
        lbl_SanPham_SearchAndAdd_LoaiDoUong = new javax.swing.JLabel();
        cbo_SanPham_SearchAndAdd_LoaiDoUong = new javax.swing.JComboBox<>();
        btn_SanPham_SearchAndAdd_Add = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_HoaDon_SanPham = new javax.swing.JTable();
        pnl_HoaDon_ThongTin = new javax.swing.JPanel();
        lbl_HoaDon_ThongTin = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl_HoaDon_ThongTin = new javax.swing.JTable();
        pnl_HoaDon_FormThongTinHD = new javax.swing.JPanel();
        pnl_FormThongTinHD_Details = new javax.swing.JPanel();
        txt_FormThongTinHD_TongTien = new javax.swing.JTextField();
        lbl_FormThongTinHD_TienThoi = new javax.swing.JLabel();
        lbl_FormThongTinHD_MaHoaDon = new javax.swing.JLabel();
        lbl_FormThongTinHD_NhanVien = new javax.swing.JLabel();
        txt_FormThongTinHD_TienKhachTra = new javax.swing.JTextField();
        lbl_FormThongTinHD_TienKhachTra = new javax.swing.JLabel();
        lbl_FormThongTinHD_TenNhanVien_Input = new javax.swing.JLabel();
        lbl_FormThongTinHD_MaHoaDon_Input = new javax.swing.JLabel();
        lbl_FormThongTinHD_Ngay_Input = new javax.swing.JLabel();
        lbl_FormThongTinHD_Ban_Input = new javax.swing.JLabel();
        lbl_FormThongTinHD_TongTien = new javax.swing.JLabel();
        lbl_FormThongTinHD_Ngay = new javax.swing.JLabel();
        txt_FormThongTin_TienThoi = new javax.swing.JTextField();
        lbl_FormThongTinHD_Ban = new javax.swing.JLabel();
        pnl_FormThongTinHD_Method = new javax.swing.JPanel();
        btn_FormThongTinHD_TaoDon = new javax.swing.JButton();
        btn_FormThongTinHD_ThanhToan = new javax.swing.JButton();
        btn_FormThongTinHD_InHoaDon = new javax.swing.JButton();

        pnl_BanHang.setLayout(new javax.swing.BoxLayout(pnl_BanHang, javax.swing.BoxLayout.LINE_AXIS));

        pnl_BanHang_Ban.setLayout(new javax.swing.BoxLayout(pnl_BanHang_Ban, javax.swing.BoxLayout.PAGE_AXIS));

        pnl_Ban_Ban.setLayout(new javax.swing.BoxLayout(pnl_Ban_Ban, javax.swing.BoxLayout.PAGE_AXIS));

        lbl_Ban_LBL.setText("Bàn");

        javax.swing.GroupLayout pnl_Ban_LBLLayout = new javax.swing.GroupLayout(pnl_Ban_LBL);
        pnl_Ban_LBL.setLayout(pnl_Ban_LBLLayout);
        pnl_Ban_LBLLayout.setHorizontalGroup(
            pnl_Ban_LBLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Ban_LBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_Ban_LBLLayout.setVerticalGroup(
            pnl_Ban_LBLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Ban_LBLLayout.createSequentialGroup()
                .addComponent(lbl_Ban_LBL)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnl_Ban_Ban.add(pnl_Ban_LBL);

        jPanel40.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jPanel40Layout = new javax.swing.GroupLayout(jPanel40);
        jPanel40.setLayout(jPanel40Layout);
        jPanel40Layout.setHorizontalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel40Layout.setVerticalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel41.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jPanel41Layout = new javax.swing.GroupLayout(jPanel41);
        jPanel41.setLayout(jPanel41Layout);
        jPanel41Layout.setHorizontalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel41Layout.setVerticalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel42.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jPanel42Layout = new javax.swing.GroupLayout(jPanel42);
        jPanel42.setLayout(jPanel42Layout);
        jPanel42Layout.setHorizontalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel42Layout.setVerticalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel43.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jPanel43Layout = new javax.swing.GroupLayout(jPanel43);
        jPanel43.setLayout(jPanel43Layout);
        jPanel43Layout.setHorizontalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel43Layout.setVerticalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel44.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jPanel44Layout = new javax.swing.GroupLayout(jPanel44);
        jPanel44.setLayout(jPanel44Layout);
        jPanel44Layout.setHorizontalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel44Layout.setVerticalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnl_Ban_ViewLayout = new javax.swing.GroupLayout(pnl_Ban_View);
        pnl_Ban_View.setLayout(pnl_Ban_ViewLayout);
        pnl_Ban_ViewLayout.setHorizontalGroup(
            pnl_Ban_ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Ban_ViewLayout.createSequentialGroup()
                .addComponent(jPanel40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnl_Ban_ViewLayout.setVerticalGroup(
            pnl_Ban_ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Ban_ViewLayout.createSequentialGroup()
                .addGroup(pnl_Ban_ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 340, Short.MAX_VALUE))
        );

        pnl_Ban_Ban.add(pnl_Ban_View);

        pnl_BanHang_Ban.add(pnl_Ban_Ban);

        pnl_Ban_GiaoHang.setLayout(new javax.swing.BoxLayout(pnl_Ban_GiaoHang, javax.swing.BoxLayout.PAGE_AXIS));

        lbl_GiaoHang_LBL.setText("Giao hàng");

        javax.swing.GroupLayout pnl_GiaoHang_LBLLayout = new javax.swing.GroupLayout(pnl_GiaoHang_LBL);
        pnl_GiaoHang_LBL.setLayout(pnl_GiaoHang_LBLLayout);
        pnl_GiaoHang_LBLLayout.setHorizontalGroup(
            pnl_GiaoHang_LBLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_GiaoHang_LBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_GiaoHang_LBLLayout.setVerticalGroup(
            pnl_GiaoHang_LBLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_GiaoHang_LBLLayout.createSequentialGroup()
                .addComponent(lbl_GiaoHang_LBL)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnl_Ban_GiaoHang.add(pnl_GiaoHang_LBL);

        jPanel52.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jPanel52Layout = new javax.swing.GroupLayout(jPanel52);
        jPanel52.setLayout(jPanel52Layout);
        jPanel52Layout.setHorizontalGroup(
            jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel52Layout.setVerticalGroup(
            jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel53.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jPanel53Layout = new javax.swing.GroupLayout(jPanel53);
        jPanel53.setLayout(jPanel53Layout);
        jPanel53Layout.setHorizontalGroup(
            jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel53Layout.setVerticalGroup(
            jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel54.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jPanel54Layout = new javax.swing.GroupLayout(jPanel54);
        jPanel54.setLayout(jPanel54Layout);
        jPanel54Layout.setHorizontalGroup(
            jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel54Layout.setVerticalGroup(
            jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel55.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jPanel55Layout = new javax.swing.GroupLayout(jPanel55);
        jPanel55.setLayout(jPanel55Layout);
        jPanel55Layout.setHorizontalGroup(
            jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel55Layout.setVerticalGroup(
            jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel56.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jPanel56Layout = new javax.swing.GroupLayout(jPanel56);
        jPanel56.setLayout(jPanel56Layout);
        jPanel56Layout.setHorizontalGroup(
            jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel56Layout.setVerticalGroup(
            jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnl_GiaoHang_ViewLayout = new javax.swing.GroupLayout(pnl_GiaoHang_View);
        pnl_GiaoHang_View.setLayout(pnl_GiaoHang_ViewLayout);
        pnl_GiaoHang_ViewLayout.setHorizontalGroup(
            pnl_GiaoHang_ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_GiaoHang_ViewLayout.createSequentialGroup()
                .addComponent(jPanel52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnl_GiaoHang_ViewLayout.setVerticalGroup(
            pnl_GiaoHang_ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_GiaoHang_ViewLayout.createSequentialGroup()
                .addGroup(pnl_GiaoHang_ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 340, Short.MAX_VALUE))
        );

        pnl_Ban_GiaoHang.add(pnl_GiaoHang_View);

        pnl_BanHang_Ban.add(pnl_Ban_GiaoHang);

        pnl_BanHang.add(pnl_BanHang_Ban);

        pnl_BanHang_HoaDon.setLayout(new javax.swing.BoxLayout(pnl_BanHang_HoaDon, javax.swing.BoxLayout.PAGE_AXIS));

        pnl_HoaDon_SanPham.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnl_HoaDon_SanPham.setLayout(new java.awt.BorderLayout());

        pnl_HoaDon_SanPham_SearchAndAdd.setLayout(new java.awt.BorderLayout());

        lbl_HoaDon_SanPham_LBL.setText("Sản phẩm");
        pnl_HoaDon_SanPham_SearchAndAdd.add(lbl_HoaDon_SanPham_LBL, java.awt.BorderLayout.PAGE_START);

        lbl_SanPham_SearchAndAdd_Search.setText("Tìm kiếm sản phẩm");

        lbl_SanPham_SearchAndAdd_LoaiDoUong.setText("Loại đồ uống");

        cbo_SanPham_SearchAndAdd_LoaiDoUong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_SanPham_SearchAndAdd_Add.setText("Thêm đồ");

        javax.swing.GroupLayout pnl_SanPham_SearchAndAddLayout = new javax.swing.GroupLayout(pnl_SanPham_SearchAndAdd);
        pnl_SanPham_SearchAndAdd.setLayout(pnl_SanPham_SearchAndAddLayout);
        pnl_SanPham_SearchAndAddLayout.setHorizontalGroup(
            pnl_SanPham_SearchAndAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_SanPham_SearchAndAddLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_SanPham_SearchAndAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_SanPham_SearchAndAdd_Search)
                    .addComponent(txt_SanPham_SearchAndAdd_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(pnl_SanPham_SearchAndAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbo_SanPham_SearchAndAdd_LoaiDoUong, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_SanPham_SearchAndAdd_LoaiDoUong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 377, Short.MAX_VALUE)
                .addComponent(btn_SanPham_SearchAndAdd_Add)
                .addGap(19, 19, 19))
        );
        pnl_SanPham_SearchAndAddLayout.setVerticalGroup(
            pnl_SanPham_SearchAndAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_SanPham_SearchAndAddLayout.createSequentialGroup()
                .addGroup(pnl_SanPham_SearchAndAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_SanPham_SearchAndAddLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_SanPham_SearchAndAdd_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_SanPham_SearchAndAddLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(pnl_SanPham_SearchAndAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_SanPham_SearchAndAdd_Search)
                            .addComponent(lbl_SanPham_SearchAndAdd_LoaiDoUong))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_SanPham_SearchAndAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_SanPham_SearchAndAdd_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbo_SanPham_SearchAndAdd_LoaiDoUong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pnl_HoaDon_SanPham_SearchAndAdd.add(pnl_SanPham_SearchAndAdd, java.awt.BorderLayout.CENTER);

        pnl_HoaDon_SanPham.add(pnl_HoaDon_SanPham_SearchAndAdd, java.awt.BorderLayout.PAGE_START);

        tbl_HoaDon_SanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tbl_HoaDon_SanPham);

        pnl_HoaDon_SanPham.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        pnl_BanHang_HoaDon.add(pnl_HoaDon_SanPham);

        pnl_HoaDon_ThongTin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnl_HoaDon_ThongTin.setLayout(new java.awt.BorderLayout());

        lbl_HoaDon_ThongTin.setText("Hóa đơn");
        pnl_HoaDon_ThongTin.add(lbl_HoaDon_ThongTin, java.awt.BorderLayout.PAGE_START);

        tbl_HoaDon_ThongTin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tbl_HoaDon_ThongTin);

        pnl_HoaDon_ThongTin.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        lbl_FormThongTinHD_TienThoi.setText("Tiền thối");

        lbl_FormThongTinHD_MaHoaDon.setText("Mã hóa đơn");

        lbl_FormThongTinHD_NhanVien.setText("Nhân viên");

        lbl_FormThongTinHD_TienKhachTra.setText("Tiền khách trả");

        lbl_FormThongTinHD_TenNhanVien_Input.setText("lbl_TenNhanVien");

        lbl_FormThongTinHD_MaHoaDon_Input.setText("lbl_MaHoaDon");

        lbl_FormThongTinHD_Ngay_Input.setText("lbl_Ngay");

        lbl_FormThongTinHD_Ban_Input.setText("lbl_Ban");

        lbl_FormThongTinHD_TongTien.setText("Tổng tiền");

        lbl_FormThongTinHD_Ngay.setText("Ngày");

        lbl_FormThongTinHD_Ban.setText("Bàn");

        javax.swing.GroupLayout pnl_FormThongTinHD_DetailsLayout = new javax.swing.GroupLayout(pnl_FormThongTinHD_Details);
        pnl_FormThongTinHD_Details.setLayout(pnl_FormThongTinHD_DetailsLayout);
        pnl_FormThongTinHD_DetailsLayout.setHorizontalGroup(
            pnl_FormThongTinHD_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_FormThongTinHD_DetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_FormThongTinHD_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_FormThongTinHD_MaHoaDon)
                    .addComponent(lbl_FormThongTinHD_TongTien)
                    .addComponent(lbl_FormThongTinHD_TienThoi)
                    .addComponent(lbl_FormThongTinHD_NhanVien))
                .addGap(18, 18, 18)
                .addGroup(pnl_FormThongTinHD_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_FormThongTinHD_TenNhanVien_Input)
                    .addGroup(pnl_FormThongTinHD_DetailsLayout.createSequentialGroup()
                        .addGroup(pnl_FormThongTinHD_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_FormThongTinHD_MaHoaDon_Input)
                            .addComponent(txt_FormThongTinHD_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_FormThongTin_TienThoi, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(pnl_FormThongTinHD_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_FormThongTinHD_DetailsLayout.createSequentialGroup()
                                .addComponent(lbl_FormThongTinHD_Ngay)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_FormThongTinHD_Ngay_Input))
                            .addGroup(pnl_FormThongTinHD_DetailsLayout.createSequentialGroup()
                                .addComponent(lbl_FormThongTinHD_TienKhachTra)
                                .addGap(18, 18, 18)
                                .addComponent(txt_FormThongTinHD_TienKhachTra, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_FormThongTinHD_DetailsLayout.createSequentialGroup()
                                .addComponent(lbl_FormThongTinHD_Ban)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_FormThongTinHD_Ban_Input)))))
                .addContainerGap())
        );
        pnl_FormThongTinHD_DetailsLayout.setVerticalGroup(
            pnl_FormThongTinHD_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_FormThongTinHD_DetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_FormThongTinHD_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_FormThongTinHD_MaHoaDon)
                    .addComponent(lbl_FormThongTinHD_MaHoaDon_Input)
                    .addComponent(lbl_FormThongTinHD_Ban)
                    .addComponent(lbl_FormThongTinHD_Ban_Input))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_FormThongTinHD_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_FormThongTinHD_TongTien)
                    .addComponent(txt_FormThongTinHD_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_FormThongTinHD_TienKhachTra)
                    .addComponent(txt_FormThongTinHD_TienKhachTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_FormThongTinHD_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_FormThongTinHD_TienThoi)
                    .addGroup(pnl_FormThongTinHD_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_FormThongTin_TienThoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_FormThongTinHD_Ngay)
                        .addComponent(lbl_FormThongTinHD_Ngay_Input)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_FormThongTinHD_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_FormThongTinHD_NhanVien)
                    .addComponent(lbl_FormThongTinHD_TenNhanVien_Input))
                .addContainerGap())
        );

        pnl_HoaDon_FormThongTinHD.add(pnl_FormThongTinHD_Details);

        btn_FormThongTinHD_TaoDon.setText("Tạo đơn");

        btn_FormThongTinHD_ThanhToan.setText("Thanh toán");

        btn_FormThongTinHD_InHoaDon.setText("In hóa đơn");

        javax.swing.GroupLayout pnl_FormThongTinHD_MethodLayout = new javax.swing.GroupLayout(pnl_FormThongTinHD_Method);
        pnl_FormThongTinHD_Method.setLayout(pnl_FormThongTinHD_MethodLayout);
        pnl_FormThongTinHD_MethodLayout.setHorizontalGroup(
            pnl_FormThongTinHD_MethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_FormThongTinHD_MethodLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_FormThongTinHD_MethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_FormThongTinHD_InHoaDon, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_FormThongTinHD_ThanhToan, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_FormThongTinHD_TaoDon, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        pnl_FormThongTinHD_MethodLayout.setVerticalGroup(
            pnl_FormThongTinHD_MethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_FormThongTinHD_MethodLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_FormThongTinHD_TaoDon)
                .addGap(17, 17, 17)
                .addComponent(btn_FormThongTinHD_ThanhToan)
                .addGap(17, 17, 17)
                .addComponent(btn_FormThongTinHD_InHoaDon)
                .addContainerGap())
        );

        pnl_HoaDon_FormThongTinHD.add(pnl_FormThongTinHD_Method);

        pnl_HoaDon_ThongTin.add(pnl_HoaDon_FormThongTinHD, java.awt.BorderLayout.PAGE_END);

        pnl_BanHang_HoaDon.add(pnl_HoaDon_ThongTin);

        pnl_BanHang.add(pnl_BanHang_HoaDon);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1457, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnl_BanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 1457, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 912, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnl_BanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 912, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_FormThongTinHD_InHoaDon;
    private javax.swing.JButton btn_FormThongTinHD_TaoDon;
    private javax.swing.JButton btn_FormThongTinHD_ThanhToan;
    private javax.swing.JButton btn_SanPham_SearchAndAdd_Add;
    private javax.swing.JComboBox<String> cbo_SanPham_SearchAndAdd_LoaiDoUong;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lbl_Ban_LBL;
    private javax.swing.JLabel lbl_FormThongTinHD_Ban;
    private javax.swing.JLabel lbl_FormThongTinHD_Ban_Input;
    private javax.swing.JLabel lbl_FormThongTinHD_MaHoaDon;
    private javax.swing.JLabel lbl_FormThongTinHD_MaHoaDon_Input;
    private javax.swing.JLabel lbl_FormThongTinHD_Ngay;
    private javax.swing.JLabel lbl_FormThongTinHD_Ngay_Input;
    private javax.swing.JLabel lbl_FormThongTinHD_NhanVien;
    private javax.swing.JLabel lbl_FormThongTinHD_TenNhanVien_Input;
    private javax.swing.JLabel lbl_FormThongTinHD_TienKhachTra;
    private javax.swing.JLabel lbl_FormThongTinHD_TienThoi;
    private javax.swing.JLabel lbl_FormThongTinHD_TongTien;
    private javax.swing.JLabel lbl_GiaoHang_LBL;
    private javax.swing.JLabel lbl_HoaDon_SanPham_LBL;
    private javax.swing.JLabel lbl_HoaDon_ThongTin;
    private javax.swing.JLabel lbl_SanPham_SearchAndAdd_LoaiDoUong;
    private javax.swing.JLabel lbl_SanPham_SearchAndAdd_Search;
    private javax.swing.JPanel pnl_BanHang;
    private javax.swing.JPanel pnl_BanHang_Ban;
    private javax.swing.JPanel pnl_BanHang_HoaDon;
    private javax.swing.JPanel pnl_Ban_Ban;
    private javax.swing.JPanel pnl_Ban_GiaoHang;
    private javax.swing.JPanel pnl_Ban_LBL;
    private javax.swing.JPanel pnl_Ban_View;
    private javax.swing.JPanel pnl_FormThongTinHD_Details;
    private javax.swing.JPanel pnl_FormThongTinHD_Method;
    private javax.swing.JPanel pnl_GiaoHang_LBL;
    private javax.swing.JPanel pnl_GiaoHang_View;
    private javax.swing.JPanel pnl_HoaDon_FormThongTinHD;
    private javax.swing.JPanel pnl_HoaDon_SanPham;
    private javax.swing.JPanel pnl_HoaDon_SanPham_SearchAndAdd;
    private javax.swing.JPanel pnl_HoaDon_ThongTin;
    private javax.swing.JPanel pnl_SanPham_SearchAndAdd;
    private javax.swing.JTable tbl_HoaDon_SanPham;
    private javax.swing.JTable tbl_HoaDon_ThongTin;
    private javax.swing.JTextField txt_FormThongTinHD_TienKhachTra;
    private javax.swing.JTextField txt_FormThongTinHD_TongTien;
    private javax.swing.JTextField txt_FormThongTin_TienThoi;
    private javax.swing.JTextField txt_SanPham_SearchAndAdd_Search;
    // End of variables declaration//GEN-END:variables
}
